# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      LD_LIBRARY_PATH: '/tmp/lib:/usr/lib:/usr/local/lib/'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install nox
      run: pip install -U nox
    - name: execute nox tests on COMMON
      working-directory: pandas-ml-common
      run: nox
    - name: execute nox tests on ML_UTILS
      working-directory: pandas-ml-utils
      run: nox
    - name: execute nox tests on ML_UTILS_TORCH
      working-directory: pandas-ml-utils-torch
      run: nox
    # - name: Install C dependencies for ml quant
    #   env:
    #     LD_LIBRARY_PATH: '/tmp/lib:/usr/lib:/usr/local/lib/'
    #     TA_LIBRARY_PATH: '/tmp/lib/'
    #     TA_INCLUDE_PATH: '/tmp/include/'
    #   run: |
    #     wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    #     tar -xzf ta-lib-0.4.0-src.tar.gz
    #     cd ta-lib/
    #     ./configure --prefix=/tmp
    #     make
    #     make install
    #     pip install TA-Lib
    # - name: execute nox tests on ML_QUANT
    #   working-directory: pandas-ml-quant
    #   run: nox
